/**
 * Orbit Energy — Amazfit Bip 6 (390 x 450)
 *
 * The dial reads as two orbits anchored to the top-right corner: the outer
 * ring carries the 24 hours, the inner ring the 60 minutes, and a glowing chip
 * marks the current position on each. Both chips grow inwards into the empty
 * centre, so they stay large without pushing the dial off-screen.
 *
 * Everything static (rings, tiles, icons, labels, pill) is baked into bg.png by
 * tools/build-assets.cjs; only the live readings are widgets. layout.js is
 * generated by the same script, so the two can never drift apart.
 *
 * Colours come in four themes. WATCHFACE_EDIT_BG puts them behind the pencil
 * icon on the watchface list and swaps the background; everything else — the
 * markers, meters, digit glyphs and every text colour — is picked from the
 * theme it reports, which is why the assets are grouped one folder per theme.
 *
 * Uses the current Zepp OS module API (@zos/ui, @zos/sensor, @zos/router). The
 * legacy globals hmSensor/hmSetting do not exist on this device.
 */

import { createWidget, deleteWidget, widget, prop, align, text_style, data_type } from '@zos/ui'
import {
  Time,
  Battery,
  Step,
  HeartRate,
  Distance,
  Calorie,
  Stress,
  Pai,
} from '@zos/sensor'
import { createSysTimer, stopTimer } from '@zos/timer'
import {
  launchApp,
  SYSTEM_APP_HR,
  SYSTEM_APP_STATUS,
  SYSTEM_APP_CALENDAR,
  SYSTEM_APP_SETTING,
  SYSTEM_APP_WEATHER,
  SYSTEM_APP_PRESSURE,
  SYSTEM_APP_PAI,
} from '@zos/router'

import {
  SCREEN,
  THEMES,
  IMAGE,
  TEMP_FONT,
  TEMP_DEGREE,
  TEMP_NEGATIVE,
  TEMP_INVALID,
  HOUR_POS,
  MINUTE_POS,
  AOD_HOUR_POS,
  AOD_MINUTE_POS,
  HL_HOUR_BOX,
  HL_MIN_BOX,
  SLOTS,
  PILL_CELLS,
  METER_STEPS,
  AOD,
} from './layout'

// There is no legacy hmUI global on this firmware — everything comes from
// @zos/ui. A few members the watchface wants are undocumented there, so each is
// probed and has a fallback.
//
// Screen states. hmUI.show_level's documented values; widgets tagged with them
// appear only in the matching state.
const LV_NORMAL = 0x1
const LV_AOD = 0x2
// Only the WATCHFACE_EDIT_BG widget carries LV_EDIT. Its `preview` is a full
// render of the whole face in the candidate theme, so any widget of ours left
// visible in edit mode paints over it in the *current* theme's colours — the
// carousel then shows two faces at once until a theme is committed.
const LV_EDIT = 0x4

const CAN_DELETE = typeof deleteWidget === 'function'
const PROP_VISIBLE = prop.VISIBLE

/**
 * WATCHFACE_EDIT_BG draws the background and, behind the pencil icon on the
 * watchface list, offers the colour themes. It reports the chosen one through
 * prop.CURRENT_TYPE. Neither the widget nor the property is in the @zos/ui
 * typings, so both are probed.
 */
const EDIT_BG_WIDGET = widget.WATCHFACE_EDIT_BG
const PROP_CURRENT_TYPE = prop.CURRENT_TYPE
const EDIT_ID = 103

/**
 * IMG_CLICK is the watchface hot zone. It does NOT take a callback: you give it
 * a `type` from data_type and the firmware jumps to whatever app owns that
 * metric. Only the date has no matching metric, so it uses a BUTTON whose
 * click_func routes through @zos/router instead.
 *
 * Neither IMG_CLICK nor the watchface-only data_type members are in the
 * @zos/ui typings, so both are probed before use.
 */
const CLICK_WIDGET = widget.IMG_CLICK

/** How often the readings are re-polled while the screen is on. */
const POLL_MS = 30000

/** Which system app each tile opens when tapped. */
const APPS = {
  HR: SYSTEM_APP_HR,
  STATUS: SYSTEM_APP_STATUS,
  CALENDAR: SYSTEM_APP_CALENDAR,
  SETTING: SYSTEM_APP_SETTING,
  WEATHER: SYSTEM_APP_WEATHER,
  PRESSURE: SYSTEM_APP_PRESSURE,
  PAI: SYSTEM_APP_PAI,
}

// Time.getDay() returns 1-7 with 1 = Monday, so index 0 is never used.
// Swap these for 'SEG', 'TER', 'QUA', … to read the date in Portuguese.
const WEEKDAYS = ['', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']

// Heart-rate zone mapped onto the little bar next to the heart icon.
const HR_MIN = 50
const HR_MAX = 180

function pad2(n) {
  return n < 10 ? '0' + n : '' + n
}

function clamp(v, lo, hi) {
  return v < lo ? lo : v > hi ? hi : v
}

/**
 * Distance comes back in metres. Kept to four characters at most so the "KM"
 * unit beside it never gets pushed out of the tile.
 */
function formatKm(metres) {
  if (!metres || metres < 0) return '0.00'
  const km = metres / 1000
  if (km < 10) return km.toFixed(2)
  if (km < 100) return km.toFixed(1)
  return String(Math.round(km))
}

WatchFace({
  onInit() {
    this.time = new Time()
    this.battery = new Battery()
    this.step = new Step()
    this.heartRate = new HeartRate()
    this.distance = new Distance()
    this.calorie = new Calorie()
    this.stress = new Stress()
    this.pai = new Pai()

    this.widgets = {}
    this.listeners = []
  },

  build() {
    this.theme = this.buildBackground()
    this.buildNormal()
    this.buildAod()
    this.buildTapZones()
    this.buildLifecycle()

    this.refreshAll()

    this.time.onPerMinute(() => this.refreshAll())

    // Steps and heart rate move far more often than once a minute.
    this.listen(this.step, 'onChange', 'offChange', () => this.refreshSteps())
    this.listen(this.heartRate, 'onCurrentChange', 'offCurrentChange', () => this.refreshHeartRate())
    this.listen(this.heartRate, 'onLastChange', 'offLastChange', () => this.refreshHeartRate())
    this.listen(this.battery, 'onChange', 'offChange', () => this.refreshBattery())
  },

  /**
   * Creates the background and settles which theme is active.
   *
   * The edit widget only ever swaps the background image — every other colour
   * and asset path in this file is chosen from the theme it reports back.
   */
  buildBackground() {
    let selected = 1

    try {
      if (EDIT_BG_WIDGET === undefined) throw new Error('WATCHFACE_EDIT_BG missing')

      const editBg = createWidget(EDIT_BG_WIDGET, {
        edit_id: EDIT_ID,
        x: 0,
        y: 0,
        w: SCREEN.w,
        h: SCREEN.h,
        bg_config: THEMES.map((t) => ({
          id: t.id,
          path: IMAGE.bg(t.key),
          preview: IMAGE.preview(t.key),
        })),
        count: THEMES.length,
        default_id: 1,
        // The stock faces pass both of these; without them the widget reports
        // no error and still initialises to nothing.
        fg: IMAGE.editorFg,
        tips_x: 178,
        tips_y: 428,
        tips_bg: IMAGE.editorTips,
        show_level: LV_NORMAL | LV_EDIT,
      })

      if (PROP_CURRENT_TYPE !== undefined) {
        selected = editBg.getProperty(PROP_CURRENT_TYPE) || 1
      }
    } catch (e) {
      console.log('orbit: no theme editor (' + e + ')')
    }

    const theme = THEMES.filter((t) => t.id === selected)[0] || THEMES[0]

    // The background is drawn here rather than left to the edit widget. On this
    // firmware that widget reported no error and still painted nothing, which
    // left the face bare; this image guarantees one either way. It is tagged
    // NORMAL only, so it never covers the editor's own carousel.
    createWidget(widget.IMG, {
      x: 0,
      y: 0,
      w: SCREEN.w,
      h: SCREEN.h,
      src: IMAGE.bg(theme.key),
      show_level: LV_NORMAL,
    })

    console.log('orbit: theme ' + theme.id + ' ' + theme.name + ' of ' + THEMES.length)
    return theme
  },

  /**
   * onPerMinute is suspended while the screen is off and does not fire on
   * wake, which is what left the minute marker stuck a few minutes behind.
   * WIDGET_DELEGATE is the watchface lifecycle hook: redraw the moment the UI
   * resumes, then re-poll on a timer for as long as it stays up.
   */
  buildLifecycle() {
    const resume = () => {
      this.refreshAll()
      this.startPolling()
    }

    try {
      createWidget(widget.WIDGET_DELEGATE, {
        resume_call: resume,
        pause_call: () => this.stopPolling(),
      })
    } catch (e) {
      console.log('orbit: no WIDGET_DELEGATE: ' + e)
    }

    this.startPolling()
  },

  startPolling() {
    if (this.timer !== undefined) return
    try {
      this.timer = createSysTimer(true, POLL_MS, () => this.refreshAll())
    } catch (e) {
      console.log('orbit: cannot start poll timer: ' + e)
    }
  },

  stopPolling() {
    if (this.timer === undefined) return
    try {
      stopTimer(this.timer)
    } catch (e) {
      console.log('orbit: cannot stop poll timer: ' + e)
    }
    this.timer = undefined
  },

  refreshAll() {
    this.refreshTime()
    this.refreshMetrics()
  },

  /** Registers a sensor listener and remembers how to tear it down. */
  listen(sensor, on, off, handler) {
    if (!sensor || typeof sensor[on] !== 'function') return
    sensor[on](handler)
    this.listeners.push({ sensor, off, handler })
  },

  // ------------------------------------------------------------- widgets --

  makeText(options) {
    return createWidget(widget.TEXT, Object.assign(
      {
        color: this.theme.color.primary,
        align_h: align.LEFT,
        align_v: align.CENTER_V,
        // NONE is the marquee style — overflowing text scrolls forever.
        // ELLIPSIS keeps it still and only trims if it ever really overruns.
        text_style: text_style.ELLIPSIS,
        text: '',
        show_level: LV_NORMAL,
      },
      options
    ))
  },

  buildNormal() {
    for (let i = 0; i < SLOTS.length; i += 1) {
      const slot = SLOTS[i]

      if (slot.meter) {
        this.widgets[slot.key + 'Meter'] = createWidget(widget.IMG, {
          x: slot.meter.x,
          y: slot.meter.y,
          w: slot.meter.w,
          h: slot.meter.h,
          src: IMAGE.meter(this.theme.key, slot.meter.name, 0),
          show_level: LV_NORMAL,
        })
      }

      this.widgets[slot.key] = this.makeText({
        x: slot.value.x,
        y: slot.value.y,
        w: slot.value.w,
        h: slot.value.h,
        text_size: slot.value.size,
        color: this.theme.color[slot.value.color],
      })

      if (slot.unit) {
        this.widgets[slot.key + 'Unit'] = this.makeText({
          x: slot.unit.x,
          y: slot.unit.y,
          w: slot.unit.w,
          h: slot.unit.h,
          text_size: slot.unit.size,
          color: this.theme.color[slot.unit.color],
          text: slot.unit.text,
        })
      }
    }

    for (let i = 0; i < PILL_CELLS.length; i += 1) {
      const cell = PILL_CELLS[i]
      if (cell.key === 'temp') {
        this.buildTemperature(cell)
      } else {
        this.widgets[cell.key] = this.makeText({
          x: cell.value.x,
          y: cell.value.y,
          w: cell.value.w,
          h: cell.value.h,
          text_size: cell.value.size,
          align_h: align.CENTER_H,
        })
      }
    }
  },

  /**
   * Current temperature is not exposed through @zos/sensor — the only source
   * is the watchface data binding, which renders from an image font. If that
   * binding is unavailable the cell simply stays blank rather than throwing.
   */
  buildTemperature(cell) {
    try {
      this.widgets.temp = createWidget(widget.TEXT_IMG, {
        x: cell.value.x,
        y: cell.value.y,
        w: cell.value.w,
        h: cell.value.h,
        type: data_type.WEATHER_CURRENT,
        font_array: TEMP_FONT(this.theme.key),
        unit_en: TEMP_DEGREE(this.theme.key),
        unit_sc: TEMP_DEGREE(this.theme.key),
        unit_tc: TEMP_DEGREE(this.theme.key),
        negative_image: TEMP_NEGATIVE(this.theme.key),
        invalid_image: TEMP_INVALID(this.theme.key),
        h_space: 0,
        align_h: align.CENTER_H,
        align_v: align.CENTER_V,
        show_level: LV_NORMAL,
      })
    } catch (e) {
      console.log('temperature widget unavailable: ' + e)
    }
  },

  /**
   * Invisible hot zones over every tile, created last so they sit above the
   * readings. Tapping one opens the matching system app, the same way the
   * stock watchfaces do.
   */
  /**
   * Hot zones over every tile, created before the orbital markers so those
   * still draw on top.
   *
   * A zone whose metric exists in data_type becomes an IMG_CLICK, which is how
   * the stock watchfaces do it: no callback, the firmware routes the tap to
   * the app that owns the metric. Anything else (the date) becomes a BUTTON
   * that calls launchApp itself.
   */
  buildTapZones() {
    const zones = SLOTS.concat(PILL_CELLS)
    let hotzones = 0
    let buttons = 0

    for (let i = 0; i < zones.length; i += 1) {
      const zone = zones[i]
      const type = zone.dataType ? data_type[zone.dataType] : undefined

      try {
        if (type !== undefined && CLICK_WIDGET !== undefined) {
          // src is painted permanently, not just while held, so it has to be
          // the transparent sprite or the tile grows a visible box
          createWidget(CLICK_WIDGET, {
            x: zone.tap.x,
            y: zone.tap.y,
            w: zone.tap.w,
            h: zone.tap.h,
            src: zone.tap.src,
            type: type,
            show_level: LV_NORMAL,
          })
          hotzones += 1
          continue
        }

        const appId = APPS[zone.app]
        if (appId === undefined) continue

        createWidget(widget.BUTTON, {
          x: zone.tap.x,
          y: zone.tap.y,
          w: zone.tap.w,
          h: zone.tap.h,
          text: '',
          normal_src: zone.tap.src,
          press_src: zone.tap.src,
          click_func: () => {
            console.log('orbit: tap ' + zone.key)
            try {
              launchApp({ appId: appId, native: true })
            } catch (e) {
              console.log('orbit: cannot open ' + zone.app + ': ' + e)
            }
          },
          show_level: LV_NORMAL,
        })
        buttons += 1
      } catch (e) {
        console.log('orbit: cannot arm tap zone ' + zone.key + ': ' + e)
      }
    }

    console.log(
      'orbit: ' + hotzones + ' IMG_CLICK zones, ' + buttons + ' buttons' +
      ' (IMG_CLICK=' + widget.IMG_CLICK + ', deleteWidget=' + CAN_DELETE + ')'
    )
  },

  buildAod() {
    createWidget(widget.IMG, {
      x: 0,
      y: 0,
      w: SCREEN.w,
      h: SCREEN.h,
      src: IMAGE.aod,
      show_level: LV_AOD,
    })

    this.widgets.aodTime = this.makeText({
      x: AOD.x,
      y: AOD.timeY,
      w: AOD.w,
      h: AOD.timeH,
      text_size: AOD.timeSize,
      color: this.theme.color.aodText,
      align_h: align.CENTER_H,
      show_level: LV_AOD,
    })

    this.widgets.aodDate = this.makeText({
      x: AOD.x,
      y: AOD.dateY,
      w: AOD.w,
      h: AOD.dateH,
      text_size: AOD.dateSize,
      color: this.theme.color.aodText,
      align_h: align.CENTER_H,
      show_level: LV_AOD,
    })
  },

  // ------------------------------------------------------------ refreshes --

  setText(name, text) {
    const w = this.widgets[name]
    if (w) w.setProperty(prop.MORE, { text: text })
  },

  /**
   * Places an orbital marker.
   *
   * The marker is re-created rather than moved. Nudging a large IMG with
   * setProperty(MORE, {x, y, src}) came back truncated on device — the hour
   * marker rendered as only the top-left 48x48 of its sprite — and re-creating
   * also re-appends the widget at the end of the display list, which is where
   * these markers belong: above every other element on the face.
   */
  placeMarker(name, pos, src, box, level) {
    const previous = this.widgets[name]
    const options = {
      x: pos[0],
      y: pos[1],
      w: box,
      h: box,
      src: src,
      show_level: level,
    }

    if (previous) {
      if (CAN_DELETE) {
        deleteWidget(previous)
      } else {
        // No deleteWidget here: restate w and h (a partial MORE patch is what
        // left the sprite truncated) and blink visibility so the old rectangle
        // is repainted cleanly.
        if (PROP_VISIBLE !== undefined) previous.setProperty(PROP_VISIBLE, false)
        previous.setProperty(prop.MORE, options)
        if (PROP_VISIBLE !== undefined) previous.setProperty(PROP_VISIBLE, true)
        return
      }
    }

    this.widgets[name] = createWidget(widget.IMG, options)
  },

  refreshTime() {
    const hour = this.time.getHours()
    const minute = this.time.getMinutes()

    if (hour !== this.lastHour) {
      this.lastHour = hour
      this.placeMarker(
        'hourChip',
        HOUR_POS[hour],
        IMAGE.hourHighlight(this.theme.key, hour),
        HL_HOUR_BOX,
        LV_NORMAL
      )
      this.placeMarker('aodHourChip', AOD_HOUR_POS[hour], IMAGE.aodHourRing, HL_HOUR_BOX, LV_AOD)
    }

    if (minute !== this.lastMinute) {
      this.lastMinute = minute
      this.placeMarker(
        'minuteChip',
        MINUTE_POS[minute],
        IMAGE.minuteHighlight(this.theme.key, minute),
        HL_MIN_BOX,
        LV_NORMAL
      )
      this.placeMarker('aodMinuteChip', AOD_MINUTE_POS[minute], IMAGE.aodMinuteRing, HL_MIN_BOX, LV_AOD)
    }

    const stamp = (WEEKDAYS[this.time.getDay()] || '') + ' ' + this.time.getDate()
    this.setText('date', stamp)
    this.setText('aodTime', pad2(hour) + ':' + pad2(minute))
    this.setText('aodDate', stamp)
  },

  /** Swaps a meter's image strip to the frame nearest `ratio` (0..1). */
  setMeter(key, name, ratio) {
    const w = this.widgets[key + 'Meter']
    if (!w) return
    const step = Math.round(clamp(ratio, 0, 1) * (METER_STEPS - 1))
    w.setProperty(prop.MORE, { src: IMAGE.meter(this.theme.key, name, step) })
  },

  refreshHeartRate() {
    const bpm = this.heartRate.getCurrent() || this.heartRate.getLast() || 0
    this.setText('hr', bpm > 0 ? '' + bpm : '--')
    this.setMeter('hr', 'hr', bpm > 0 ? (bpm - HR_MIN) / (HR_MAX - HR_MIN) : 0)
  },

  refreshSteps() {
    this.setText('steps', '' + this.step.getCurrent())
  },

  refreshBattery() {
    const level = clamp(this.battery.getCurrent(), 0, 100)
    this.setText('battery', '' + level)
    this.setMeter('battery', 'battery', level / 100)
  },

  refreshMetrics() {
    this.refreshHeartRate()
    this.refreshSteps()
    this.refreshBattery()

    this.setText('distance', formatKm(this.distance.getCurrent()))

    this.setText('kcal', '' + this.calorie.getCurrent())

    const stress = this.stress.getCurrent()
    this.setText('stress', stress && stress.value > 0 ? '' + stress.value : '--')

    // getToday() is only what was earned since midnight, so it reads 0 for
    // most of the day. getTotal() is the rolling 7-day score — the number the
    // watch's own PAI screen shows.
    this.setText('pai', '' + Math.round(this.pai.getTotal() || 0))
  },

  onDestroy() {
    this.stopPolling()
    if (!this.listeners) return
    for (let i = 0; i < this.listeners.length; i += 1) {
      const l = this.listeners[i]
      if (typeof l.sensor[l.off] === 'function') l.sensor[l.off](l.handler)
    }
    this.listeners = []
  },
})
