/**
 * Orbit Energy — Amazfit Bip 6 (390 x 450)
 *
 * The dial reads as two orbits: the outer ring carries the 24 hours, the inner
 * ring the 60 minutes, and a glowing chip marks the current position on each.
 *
 * Everything static (rings, icons, labels, pill) is baked into bg.png by
 * tools/build-assets.cjs; only the live readings are widgets. layout.js is
 * generated by the same script, so the two can never drift apart.
 *
 * Uses the current Zepp OS module API (@zos/ui, @zos/sensor). The legacy
 * globals hmSensor/hmSetting do not exist on this device.
 */

import { createWidget, widget, prop, align, text_style, data_type } from '@zos/ui'
import {
  Time,
  Battery,
  Step,
  HeartRate,
  Distance,
  Stand,
  Calorie,
  Stress,
  Pai,
} from '@zos/sensor'

import {
  SCREEN,
  COLOR,
  IMAGE,
  TEMP_FONT,
  TEMP_DEGREE,
  TEMP_NEGATIVE,
  TEMP_INVALID,
  HOUR_POS,
  MINUTE_POS,
  AOD_HOUR_POS,
  AOD_MINUTE_POS,
  HL_HOUR_BOX,
  HL_MIN_BOX,
  COL,
  ROW,
  VALUE_BOX,
  UNIT_BOX,
  HR_BAR,
  BAT,
  PILL,
  AOD,
} from './layout'

// Widgets are tagged with the screen states they belong to. The constants live
// on the global hmUI object on device; the literals are the documented values
// and act as a fallback so a missing global can never blank the face.
const SHOW = (typeof hmUI !== 'undefined' && hmUI.show_level) || {}
const LV_NORMAL = SHOW.ONLY_NORMAL || 0x1
const LV_AOD = SHOW.ONLY_AOD || 0x2
const LV_EDIT = SHOW.ONLY_EDIT || 0x4

// Time.getDay() returns 1-7 with 1 = Monday, so index 0 is never used.
// Swap these for 'SEG', 'TER', 'QUA', … to read the date in Portuguese.
const WEEKDAYS = ['', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']

// Heart-rate zone mapped onto the little bar next to the heart icon.
const HR_MIN = 50
const HR_MAX = 180

function pad2(n) {
  return n < 10 ? '0' + n : '' + n
}

function clamp(v, lo, hi) {
  return v < lo ? lo : v > hi ? hi : v
}

/** Distance comes back in metres; the face shows kilometres with 2 decimals. */
function formatKm(metres) {
  if (!metres || metres < 0) return '0.00'
  const km = metres / 1000
  return km >= 100 ? km.toFixed(1) : km.toFixed(2)
}

WatchFace({
  onInit() {
    this.time = new Time()
    this.battery = new Battery()
    this.step = new Step()
    this.heartRate = new HeartRate()
    this.distance = new Distance()
    this.stand = new Stand()
    this.calorie = new Calorie()
    this.stress = new Stress()
    this.pai = new Pai()

    this.widgets = {}
    this.listeners = []
  },

  build() {
    this.buildNormal()
    this.buildAod()

    this.refreshTime()
    this.refreshMetrics()

    this.time.onPerMinute(() => {
      this.refreshTime()
      this.refreshMetrics()
    })

    // Steps and heart rate move far more often than once a minute.
    this.listen(this.step, 'onChange', 'offChange', () => this.refreshSteps())
    this.listen(this.heartRate, 'onCurrentChange', 'offCurrentChange', () => this.refreshHeartRate())
    this.listen(this.heartRate, 'onLastChange', 'offLastChange', () => this.refreshHeartRate())
    this.listen(this.battery, 'onChange', 'offChange', () => this.refreshBattery())
  },

  /** Registers a sensor listener and remembers how to tear it down. */
  listen(sensor, on, off, handler) {
    if (!sensor || typeof sensor[on] !== 'function') return
    sensor[on](handler)
    this.listeners.push({ sensor, off, handler })
  },

  // ------------------------------------------------------------- widgets --

  makeText(options) {
    return createWidget(widget.TEXT, Object.assign(
      {
        color: COLOR.pink,
        align_h: align.LEFT,
        align_v: align.CENTER_V,
        text_style: text_style.NONE,
        text: '',
        show_level: LV_NORMAL | LV_EDIT,
      },
      options
    ))
  },

  /** A big value plus its smaller trailing unit, sharing one baseline. */
  valueRow(key, valueColor, unitText, unitColor) {
    const box = VALUE_BOX[key]
    this.widgets[key] = this.makeText({
      x: box.x,
      y: ROW[key],
      w: box.w,
      h: COL.valueH,
      text_size: key === 'date' ? COL.valueSize - 2 : COL.valueSize,
      color: valueColor,
    })

    const unit = UNIT_BOX[key]
    if (!unit) return
    this.widgets[key + 'Unit'] = this.makeText({
      x: unit.x,
      y: ROW[key] + COL.unitDy,
      w: unit.w,
      h: COL.unitH,
      text_size: unit.size,
      color: unitColor,
      text: unitText || '',
    })
  },

  buildNormal() {
    createWidget(widget.IMG, {
      x: 0,
      y: 0,
      w: SCREEN.w,
      h: SCREEN.h,
      src: IMAGE.bg,
      show_level: LV_NORMAL | LV_EDIT,
    })

    // orbital highlights — one sprite each, repositioned every minute
    this.widgets.hourChip = createWidget(widget.IMG, {
      x: HOUR_POS[0][0],
      y: HOUR_POS[0][1],
      w: HL_HOUR_BOX,
      h: HL_HOUR_BOX,
      src: IMAGE.hourHighlight(0),
      show_level: LV_NORMAL | LV_EDIT,
    })

    this.widgets.minuteChip = createWidget(widget.IMG, {
      x: MINUTE_POS[0][0],
      y: MINUTE_POS[0][1],
      w: HL_MIN_BOX,
      h: HL_MIN_BOX,
      src: IMAGE.minuteHighlight(0),
      show_level: LV_NORMAL | LV_EDIT,
    })

    // heart-rate zone bar (the track is part of the background)
    this.widgets.hrBar = createWidget(widget.FILL_RECT, {
      x: HR_BAR.x,
      y: HR_BAR.y,
      w: 1,
      h: HR_BAR.h,
      radius: HR_BAR.h / 2,
      color: COLOR.pink,
      show_level: LV_NORMAL | LV_EDIT,
    })

    this.valueRow('hr', COLOR.pink, 'BPM', COLOR.white)
    this.valueRow('distance', COLOR.pink, 'KM', COLOR.blue)
    this.valueRow('steps', COLOR.pink)
    this.valueRow('date', COLOR.pink)
    this.valueRow('stand', COLOR.pink, '', COLOR.cyan)

    this.widgets.battery = this.makeText({
      x: BAT.valueX,
      y: BAT.valueY,
      w: BAT.valueW,
      h: BAT.valueH,
      text_size: BAT.valueSize,
      color: COLOR.cyan,
    })

    this.widgets.wave = createWidget(widget.IMG, {
      x: BAT.waveX,
      y: BAT.waveY,
      w: BAT.waveW,
      h: BAT.waveH,
      src: IMAGE.wave(0),
      show_level: LV_NORMAL | LV_EDIT,
    })

    // bottom pill: Temp | Kcal | Stress | PAI
    this.buildTemperature()
    this.widgets.kcal = this.pillValue(1)
    this.widgets.stress = this.pillValue(2)
    this.widgets.pai = this.pillValue(3)
  },

  pillValue(index) {
    return this.makeText({
      x: PILL.centers[index] - PILL.cellW / 2,
      y: PILL.valueY,
      w: PILL.cellW,
      h: PILL.valueH,
      text_size: PILL.valueSize,
      color: COLOR.pink,
      align_h: align.CENTER_H,
    })
  },

  /**
   * Current temperature is not exposed through @zos/sensor — the only source
   * is the watchface data binding, which renders from an image font. If that
   * binding is unavailable the cell simply stays blank rather than throwing.
   */
  buildTemperature() {
    try {
      this.widgets.temp = createWidget(widget.TEXT_IMG, {
        x: PILL.centers[0] - PILL.cellW / 2,
        y: PILL.valueY,
        w: PILL.cellW,
        h: PILL.valueH,
        type: data_type.WEATHER_CURRENT,
        font_array: TEMP_FONT,
        unit_en: TEMP_DEGREE,
        unit_sc: TEMP_DEGREE,
        unit_tc: TEMP_DEGREE,
        negative_image: TEMP_NEGATIVE,
        invalid_image: TEMP_INVALID,
        h_space: 0,
        align_h: align.CENTER_H,
        align_v: align.CENTER_V,
        show_level: LV_NORMAL | LV_EDIT,
      })
    } catch (e) {
      console.log('temperature widget unavailable: ' + e)
    }
  },

  buildAod() {
    createWidget(widget.IMG, {
      x: 0,
      y: 0,
      w: SCREEN.w,
      h: SCREEN.h,
      src: IMAGE.aod,
      show_level: LV_AOD,
    })

    this.widgets.aodHourChip = createWidget(widget.IMG, {
      x: AOD_HOUR_POS[0][0],
      y: AOD_HOUR_POS[0][1],
      w: HL_HOUR_BOX,
      h: HL_HOUR_BOX,
      src: IMAGE.aodHourRing,
      show_level: LV_AOD,
    })

    this.widgets.aodMinuteChip = createWidget(widget.IMG, {
      x: AOD_MINUTE_POS[0][0],
      y: AOD_MINUTE_POS[0][1],
      w: HL_MIN_BOX,
      h: HL_MIN_BOX,
      src: IMAGE.aodMinuteRing,
      show_level: LV_AOD,
    })

    this.widgets.aodTime = this.makeText({
      x: AOD.x,
      y: AOD.timeY,
      w: AOD.w,
      h: AOD.timeH,
      text_size: AOD.timeSize,
      color: COLOR.aodText,
      align_h: align.CENTER_H,
      show_level: LV_AOD,
    })

    this.widgets.aodDate = this.makeText({
      x: AOD.x,
      y: AOD.dateY,
      w: AOD.w,
      h: AOD.dateH,
      text_size: AOD.dateSize,
      color: COLOR.aodText,
      align_h: align.CENTER_H,
      show_level: LV_AOD,
    })
  },

  // ------------------------------------------------------------ refreshes --

  setText(name, text) {
    const w = this.widgets[name]
    if (w) w.setProperty(prop.MORE, { text: text })
  },

  moveTo(name, pos, src) {
    const w = this.widgets[name]
    if (!w) return
    const patch = { x: pos[0], y: pos[1] }
    if (src) patch.src = src
    w.setProperty(prop.MORE, patch)
  },

  refreshTime() {
    const hour = this.time.getHours()
    const minute = this.time.getMinutes()

    this.moveTo('hourChip', HOUR_POS[hour], IMAGE.hourHighlight(hour))
    this.moveTo('minuteChip', MINUTE_POS[minute], IMAGE.minuteHighlight(minute))
    this.moveTo('aodHourChip', AOD_HOUR_POS[hour])
    this.moveTo('aodMinuteChip', AOD_MINUTE_POS[minute])

    const weekday = WEEKDAYS[this.time.getDay()] || ''
    this.setText('date', weekday + ' ' + this.time.getDate())
    this.setText('aodTime', pad2(hour) + ':' + pad2(minute))
    this.setText('aodDate', weekday + ' ' + this.time.getDate())
  },

  refreshHeartRate() {
    const bpm = this.heartRate.getCurrent() || this.heartRate.getLast() || 0
    this.setText('hr', bpm > 0 ? '' + bpm : '--')

    const ratio = bpm > 0 ? clamp((bpm - HR_MIN) / (HR_MAX - HR_MIN), 0, 1) : 0
    const w = this.widgets.hrBar
    if (w) w.setProperty(prop.MORE, { w: Math.max(Math.round(HR_BAR.w * ratio), ratio > 0 ? HR_BAR.h : 1) })
  },

  refreshSteps() {
    this.setText('steps', '' + this.step.getCurrent())
  },

  refreshBattery() {
    const level = clamp(this.battery.getCurrent(), 0, 100)
    this.setText('battery', '' + level)

    const step = Math.round((level / 100) * (BAT.waveSteps - 1))
    const w = this.widgets.wave
    if (w) w.setProperty(prop.MORE, { src: IMAGE.wave(step) })
  },

  refreshMetrics() {
    this.refreshHeartRate()
    this.refreshSteps()
    this.refreshBattery()

    this.setText('distance', formatKm(this.distance.getCurrent()))

    const stand = this.stand.getCurrent()
    const standTarget = this.stand.getTarget() || 12
    this.setText('stand', '' + stand)
    this.setText('standUnit', '/' + standTarget)

    this.setText('kcal', '' + this.calorie.getCurrent())

    const stress = this.stress.getCurrent()
    const stressValue = stress && stress.value > 0 ? stress.value : null
    this.setText('stress', stressValue ? '' + stressValue : '--')

    this.setText('pai', '' + (this.pai.getToday() || 0))
  },

  onDestroy() {
    if (!this.listeners) return
    for (let i = 0; i < this.listeners.length; i += 1) {
      const l = this.listeners[i]
      if (typeof l.sensor[l.off] === 'function') l.sensor[l.off](l.handler)
    }
    this.listeners = []
  },
})
