/**
 * Orbit Energy — Amazfit Bip 6 (390 x 450)
 *
 * The dial reads as two orbits anchored to the top-right corner: the outer
 * ring carries the 24 hours, the inner ring the 60 minutes, and a glowing chip
 * marks the current position on each. Both chips grow inwards into the empty
 * centre, so they stay large without pushing the dial off-screen.
 *
 * Everything static (rings, tiles, icons, labels, pill) is baked into bg.png by
 * tools/build-assets.cjs; only the live readings are widgets. layout.js is
 * generated by the same script, so the two can never drift apart.
 *
 * Uses the current Zepp OS module API (@zos/ui, @zos/sensor, @zos/router). The
 * legacy globals hmSensor/hmSetting do not exist on this device.
 */

import { createWidget, widget, prop, align, text_style, data_type } from '@zos/ui'
import {
  Time,
  Battery,
  Step,
  HeartRate,
  Distance,
  Stand,
  Calorie,
  Stress,
  Pai,
} from '@zos/sensor'
import {
  launchApp,
  SYSTEM_APP_HR,
  SYSTEM_APP_STATUS,
  SYSTEM_APP_CALENDAR,
  SYSTEM_APP_SETTING,
  SYSTEM_APP_WEATHER,
  SYSTEM_APP_PRESSURE,
  SYSTEM_APP_PAI,
} from '@zos/router'

import {
  SCREEN,
  COLOR,
  IMAGE,
  TEMP_FONT,
  TEMP_DEGREE,
  TEMP_NEGATIVE,
  TEMP_INVALID,
  HOUR_POS,
  MINUTE_POS,
  AOD_HOUR_POS,
  AOD_MINUTE_POS,
  HL_HOUR_BOX,
  HL_MIN_BOX,
  SLOTS,
  PILL_CELLS,
  WAVE_STEPS,
  AOD,
} from './layout'

// Widgets are tagged with the screen states they belong to. The constants live
// on the global hmUI object on device; the literals are the documented values
// and act as a fallback so a missing global can never blank the face.
const SHOW = (typeof hmUI !== 'undefined' && hmUI.show_level) || {}
const LV_NORMAL = SHOW.ONLY_NORMAL || 0x1
const LV_AOD = SHOW.ONLY_AOD || 0x2
const LV_EDIT = SHOW.ONLY_EDIT || 0x4

/** Which system app each tile opens when tapped. */
const APPS = {
  HR: SYSTEM_APP_HR,
  STATUS: SYSTEM_APP_STATUS,
  CALENDAR: SYSTEM_APP_CALENDAR,
  SETTING: SYSTEM_APP_SETTING,
  WEATHER: SYSTEM_APP_WEATHER,
  PRESSURE: SYSTEM_APP_PRESSURE,
  PAI: SYSTEM_APP_PAI,
}

// Time.getDay() returns 1-7 with 1 = Monday, so index 0 is never used.
// Swap these for 'SEG', 'TER', 'QUA', … to read the date in Portuguese.
const WEEKDAYS = ['', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']

// Heart-rate zone mapped onto the little bar next to the heart icon.
const HR_MIN = 50
const HR_MAX = 180

function pad2(n) {
  return n < 10 ? '0' + n : '' + n
}

function clamp(v, lo, hi) {
  return v < lo ? lo : v > hi ? hi : v
}

/**
 * Distance comes back in metres. Kept to four characters at most so the "KM"
 * unit beside it never gets pushed out of the tile.
 */
function formatKm(metres) {
  if (!metres || metres < 0) return '0.00'
  const km = metres / 1000
  if (km < 10) return km.toFixed(2)
  if (km < 100) return km.toFixed(1)
  return String(Math.round(km))
}

WatchFace({
  onInit() {
    this.time = new Time()
    this.battery = new Battery()
    this.step = new Step()
    this.heartRate = new HeartRate()
    this.distance = new Distance()
    this.stand = new Stand()
    this.calorie = new Calorie()
    this.stress = new Stress()
    this.pai = new Pai()

    this.widgets = {}
    this.listeners = []
  },

  build() {
    this.buildNormal()
    this.buildAod()
    this.buildTapZones()

    this.refreshTime()
    this.refreshMetrics()

    this.time.onPerMinute(() => {
      this.refreshTime()
      this.refreshMetrics()
    })

    // Steps and heart rate move far more often than once a minute.
    this.listen(this.step, 'onChange', 'offChange', () => this.refreshSteps())
    this.listen(this.heartRate, 'onCurrentChange', 'offCurrentChange', () => this.refreshHeartRate())
    this.listen(this.heartRate, 'onLastChange', 'offLastChange', () => this.refreshHeartRate())
    this.listen(this.battery, 'onChange', 'offChange', () => this.refreshBattery())
  },

  /** Registers a sensor listener and remembers how to tear it down. */
  listen(sensor, on, off, handler) {
    if (!sensor || typeof sensor[on] !== 'function') return
    sensor[on](handler)
    this.listeners.push({ sensor, off, handler })
  },

  // ------------------------------------------------------------- widgets --

  makeText(options) {
    return createWidget(widget.TEXT, Object.assign(
      {
        color: COLOR.pink,
        align_h: align.LEFT,
        align_v: align.CENTER_V,
        text_style: text_style.NONE,
        text: '',
        show_level: LV_NORMAL | LV_EDIT,
      },
      options
    ))
  },

  buildNormal() {
    createWidget(widget.IMG, {
      x: 0,
      y: 0,
      w: SCREEN.w,
      h: SCREEN.h,
      src: IMAGE.bg,
      show_level: LV_NORMAL | LV_EDIT,
    })

    // orbital highlights — one sprite each, repositioned every minute
    this.widgets.hourChip = createWidget(widget.IMG, {
      x: HOUR_POS[0][0],
      y: HOUR_POS[0][1],
      w: HL_HOUR_BOX,
      h: HL_HOUR_BOX,
      src: IMAGE.hourHighlight(0),
      show_level: LV_NORMAL | LV_EDIT,
    })

    this.widgets.minuteChip = createWidget(widget.IMG, {
      x: MINUTE_POS[0][0],
      y: MINUTE_POS[0][1],
      w: HL_MIN_BOX,
      h: HL_MIN_BOX,
      src: IMAGE.minuteHighlight(0),
      show_level: LV_NORMAL | LV_EDIT,
    })

    for (let i = 0; i < SLOTS.length; i += 1) {
      const slot = SLOTS[i]

      // The gauge track and the dim wave are baked into the background; these
      // are the lit overlays that sit on top of them.
      if (slot.gauge) {
        this.widgets[slot.key + 'Gauge'] = createWidget(widget.FILL_RECT, {
          x: slot.gauge.x,
          y: slot.gauge.y,
          w: 1,
          h: slot.gauge.h,
          radius: slot.gauge.h / 2,
          color: COLOR.pink,
          show_level: LV_NORMAL | LV_EDIT,
        })
      }

      if (slot.wave) {
        this.widgets[slot.key + 'Wave'] = createWidget(widget.IMG, {
          x: slot.wave.x,
          y: slot.wave.y,
          w: slot.wave.w,
          h: slot.wave.h,
          src: IMAGE.wave(0),
          show_level: LV_NORMAL | LV_EDIT,
        })
      }

      this.widgets[slot.key] = this.makeText({
        x: slot.value.x,
        y: slot.value.y,
        w: slot.value.w,
        h: slot.value.h,
        text_size: slot.value.size,
        color: slot.value.color,
      })

      if (slot.unit) {
        this.widgets[slot.key + 'Unit'] = this.makeText({
          x: slot.unit.x,
          y: slot.unit.y,
          w: slot.unit.w,
          h: slot.unit.h,
          text_size: slot.unit.size,
          color: slot.unit.color,
          text: slot.unit.text,
        })
      }
    }

    for (let i = 0; i < PILL_CELLS.length; i += 1) {
      const cell = PILL_CELLS[i]
      if (cell.key === 'temp') {
        this.buildTemperature(cell)
      } else {
        this.widgets[cell.key] = this.makeText({
          x: cell.value.x,
          y: cell.value.y,
          w: cell.value.w,
          h: cell.value.h,
          text_size: cell.value.size,
          align_h: align.CENTER_H,
        })
      }
    }
  },

  /**
   * Current temperature is not exposed through @zos/sensor — the only source
   * is the watchface data binding, which renders from an image font. If that
   * binding is unavailable the cell simply stays blank rather than throwing.
   */
  buildTemperature(cell) {
    try {
      this.widgets.temp = createWidget(widget.TEXT_IMG, {
        x: cell.value.x,
        y: cell.value.y,
        w: cell.value.w,
        h: cell.value.h,
        type: data_type.WEATHER_CURRENT,
        font_array: TEMP_FONT,
        unit_en: TEMP_DEGREE,
        unit_sc: TEMP_DEGREE,
        unit_tc: TEMP_DEGREE,
        negative_image: TEMP_NEGATIVE,
        invalid_image: TEMP_INVALID,
        h_space: 0,
        align_h: align.CENTER_H,
        align_v: align.CENTER_V,
        show_level: LV_NORMAL | LV_EDIT,
      })
    } catch (e) {
      console.log('temperature widget unavailable: ' + e)
    }
  },

  /**
   * Invisible hot zones over every tile, created last so they sit above the
   * readings. Tapping one opens the matching system app, the same way the
   * stock watchfaces do.
   */
  buildTapZones() {
    const zones = SLOTS.concat(PILL_CELLS)

    for (let i = 0; i < zones.length; i += 1) {
      const zone = zones[i]
      const appId = APPS[zone.app]
      if (appId === undefined) continue

      const open = () => {
        try {
          launchApp({ appId: appId, native: true })
        } catch (e) {
          console.log('cannot open ' + zone.app + ': ' + e)
        }
      }

      const options = {
        x: zone.tap.x,
        y: zone.tap.y,
        w: zone.tap.w,
        h: zone.tap.h,
        src: zone.tap.src,
        show_level: LV_NORMAL,
      }

      // IMG_CLICK is the watchface hot-zone widget; fall back to a plain image
      // with a release handler on builds that do not expose it.
      if (widget.IMG_CLICK) {
        options.click_func = open
      } else {
        options.click_up = open
      }

      try {
        createWidget(widget.IMG_CLICK || widget.IMG, options)
      } catch (e) {
        console.log('cannot arm tap zone ' + zone.key + ': ' + e)
      }
    }
  },

  buildAod() {
    createWidget(widget.IMG, {
      x: 0,
      y: 0,
      w: SCREEN.w,
      h: SCREEN.h,
      src: IMAGE.aod,
      show_level: LV_AOD,
    })

    this.widgets.aodHourChip = createWidget(widget.IMG, {
      x: AOD_HOUR_POS[0][0],
      y: AOD_HOUR_POS[0][1],
      w: HL_HOUR_BOX,
      h: HL_HOUR_BOX,
      src: IMAGE.aodHourRing,
      show_level: LV_AOD,
    })

    this.widgets.aodMinuteChip = createWidget(widget.IMG, {
      x: AOD_MINUTE_POS[0][0],
      y: AOD_MINUTE_POS[0][1],
      w: HL_MIN_BOX,
      h: HL_MIN_BOX,
      src: IMAGE.aodMinuteRing,
      show_level: LV_AOD,
    })

    this.widgets.aodTime = this.makeText({
      x: AOD.x,
      y: AOD.timeY,
      w: AOD.w,
      h: AOD.timeH,
      text_size: AOD.timeSize,
      color: COLOR.aodText,
      align_h: align.CENTER_H,
      show_level: LV_AOD,
    })

    this.widgets.aodDate = this.makeText({
      x: AOD.x,
      y: AOD.dateY,
      w: AOD.w,
      h: AOD.dateH,
      text_size: AOD.dateSize,
      color: COLOR.aodText,
      align_h: align.CENTER_H,
      show_level: LV_AOD,
    })
  },

  // ------------------------------------------------------------ refreshes --

  setText(name, text) {
    const w = this.widgets[name]
    if (w) w.setProperty(prop.MORE, { text: text })
  },

  moveTo(name, pos, src) {
    const w = this.widgets[name]
    if (!w) return
    const patch = { x: pos[0], y: pos[1] }
    if (src) patch.src = src
    w.setProperty(prop.MORE, patch)
  },

  refreshTime() {
    const hour = this.time.getHours()
    const minute = this.time.getMinutes()

    this.moveTo('hourChip', HOUR_POS[hour], IMAGE.hourHighlight(hour))
    this.moveTo('minuteChip', MINUTE_POS[minute], IMAGE.minuteHighlight(minute))
    this.moveTo('aodHourChip', AOD_HOUR_POS[hour])
    this.moveTo('aodMinuteChip', AOD_MINUTE_POS[minute])

    const stamp = (WEEKDAYS[this.time.getDay()] || '') + ' ' + this.time.getDate()
    this.setText('date', stamp)
    this.setText('aodTime', pad2(hour) + ':' + pad2(minute))
    this.setText('aodDate', stamp)
  },

  refreshHeartRate() {
    const bpm = this.heartRate.getCurrent() || this.heartRate.getLast() || 0
    this.setText('hr', bpm > 0 ? '' + bpm : '--')

    const track = SLOTS[0].gauge
    const gauge = this.widgets.hrGauge
    if (!gauge || !track) return

    const ratio = bpm > 0 ? clamp((bpm - HR_MIN) / (HR_MAX - HR_MIN), 0, 1) : 0
    const width = Math.round(track.w * ratio)
    gauge.setProperty(prop.MORE, { w: Math.max(width, ratio > 0 ? track.h : 1) })
  },

  refreshSteps() {
    this.setText('steps', '' + this.step.getCurrent())
  },

  refreshBattery() {
    const level = clamp(this.battery.getCurrent(), 0, 100)
    this.setText('battery', '' + level)

    const wave = this.widgets.batteryWave
    if (wave) {
      wave.setProperty(prop.MORE, { src: IMAGE.wave(Math.round((level / 100) * (WAVE_STEPS - 1))) })
    }
  },

  refreshMetrics() {
    this.refreshHeartRate()
    this.refreshSteps()
    this.refreshBattery()

    this.setText('distance', formatKm(this.distance.getCurrent()))

    this.setText('stand', '' + this.stand.getCurrent())
    this.setText('standUnit', '/' + (this.stand.getTarget() || 12))

    this.setText('kcal', '' + this.calorie.getCurrent())

    const stress = this.stress.getCurrent()
    this.setText('stress', stress && stress.value > 0 ? '' + stress.value : '--')

    this.setText('pai', '' + (this.pai.getToday() || 0))
  },

  onDestroy() {
    if (!this.listeners) return
    for (let i = 0; i < this.listeners.length; i += 1) {
      const l = this.listeners[i]
      if (typeof l.sensor[l.off] === 'function') l.sensor[l.off](l.handler)
    }
    this.listeners = []
  },
})
