/**
 * GENERATED by tools/build-assets.cjs — do not edit by hand.
 * Keeps the live widgets aligned with the baked-in background artwork.
 */

export const SCREEN = { w: 390, h: 450 }

export const COLOR = {
  bg: 0x000000,
  pink: 0xf24bcf,
  cyan: 0x0be0f2,
  white: 0xffffff,
  aodText: 0xc8c8d8,
}

export const IMAGE = {
  bg: 'bg.png',
  aod: 'aod.png',
  hourHighlight: (h) => 'hl/h' + (h < 10 ? '0' + h : h) + '.png',
  minuteHighlight: (m) => 'hl/m' + (m < 10 ? '0' + m : m) + '.png',
  meter: (name, step) => 'meter/' + name + '/' + (step < 10 ? '0' + step : step) + '.png',
  aodHourRing: 'hl/aod_h.png',
  aodMinuteRing: 'hl/aod_m.png',
}

export const TEMP_FONT = [
  'temp/0.png', 'temp/1.png', 'temp/2.png', 'temp/3.png', 'temp/4.png',
  'temp/5.png', 'temp/6.png', 'temp/7.png', 'temp/8.png', 'temp/9.png',
]
export const TEMP_DEGREE = 'temp/deg.png'
export const TEMP_NEGATIVE = 'temp/neg.png'
export const TEMP_INVALID = 'temp/dash.png'

/** Top-left corner of the 66x66 hour chip, per hour. */
export const HOUR_POS = [[228,21],[252,24],[275,34],[294,49],[309,68],[319,91],[322,115],[319,139],[309,162],[294,181],[275,196],[252,206],[228,209],[204,206],[181,196],[162,181],[147,162],[137,139],[134,115],[137,91],[147,68],[162,49],[181,34],[204,24]]
/** Top-left corner of the 60x60 minute chip, per minute. */
export const MINUTE_POS = [[231,84],[235,84],[238,85],[242,86],[245,87],[248,89],[251,90],[254,93],[256,95],[259,98],[260,101],[262,104],[263,107],[264,111],[265,114],[265,118],[265,122],[264,125],[263,129],[262,132],[260,135],[259,138],[256,141],[254,143],[251,146],[248,147],[245,149],[242,150],[238,151],[235,152],[231,152],[227,152],[224,151],[220,150],[217,149],[214,147],[211,146],[208,143],[206,141],[203,138],[202,135],[200,132],[199,129],[198,125],[197,122],[197,118],[197,114],[198,111],[199,107],[200,104],[202,101],[203,98],[206,95],[208,93],[211,90],[214,89],[217,87],[220,86],[224,85],[227,84]]
/** Same sprites, positioned around the centred AOD dial. */
export const AOD_HOUR_POS = [[162,33],[199,38],[234,52],[264,75],[287,105],[301,140],[306,177],[301,214],[287,249],[264,279],[234,302],[199,316],[162,321],[125,316],[90,302],[60,279],[37,249],[23,214],[18,177],[23,140],[37,105],[60,75],[90,52],[125,38]]
export const AOD_MINUTE_POS = [[165,98],[174,98],[182,100],[190,102],[198,105],[206,109],[213,114],[220,119],[226,125],[231,132],[236,139],[240,147],[243,155],[245,163],[247,171],[247,180],[247,189],[245,197],[243,205],[240,213],[236,221],[231,228],[226,235],[220,241],[213,246],[206,251],[198,255],[190,258],[182,260],[174,262],[165,262],[156,262],[148,260],[140,258],[132,255],[124,251],[117,246],[110,241],[104,235],[99,228],[94,221],[90,213],[87,205],[85,197],[83,189],[83,180],[83,171],[85,163],[87,155],[90,147],[94,139],[99,132],[104,125],[110,119],[117,114],[124,109],[132,105],[140,102],[148,100],[156,98]]

export const HL_HOUR_BOX = 66
export const HL_MIN_BOX = 60

/**
 * One entry per tile: the live value box, its optional trailing unit, the
 * heart-rate gauge or battery wave, the tap target, and the name of the system
 * app that a tap opens.
 */
export const SLOTS = [{"key":"hr","app":"HR","tap":{"src":"hit/120x78.png","x":12,"y":28,"w":120,"h":78},"value":{"x":24,"y":64,"w":54,"h":36,"size":31,"color":0xf24bcf},"unit":{"x":78,"y":76,"w":48,"h":24,"size":15,"color":0xffffff,"text":"BPM"},"meter":{"name":"hr","x":52,"y":39,"w":66,"h":14},"dataType":"HEART"},{"key":"distance","app":"STATUS","tap":{"src":"hit/120x78.png","x":12,"y":112,"w":120,"h":78},"value":{"x":24,"y":148,"w":64,"h":36,"size":31,"color":0xf24bcf},"unit":{"x":88,"y":160,"w":36,"h":24,"size":15,"color":0x7175ff,"text":"KM"},"meter":null,"dataType":"DISTANCE"},{"key":"steps","app":"STATUS","tap":{"src":"hit/120x78.png","x":12,"y":196,"w":120,"h":78},"value":{"x":24,"y":232,"w":96,"h":36,"size":31,"color":0xf24bcf},"unit":null,"meter":null,"dataType":"STEP"},{"key":"date","app":"CALENDAR","tap":{"src":"hit/150x68.png","x":12,"y":280,"w":150,"h":68},"value":{"x":24,"y":306,"w":126,"h":36,"size":29,"color":0xf24bcf},"unit":null,"meter":null,"dataType":null},{"key":"battery","app":"SETTING","tap":{"src":"hit/210x68.png","x":170,"y":280,"w":210,"h":68},"value":{"x":182,"y":306,"w":52,"h":36,"size":29,"color":0x0be0f2},"unit":null,"meter":{"name":"battery","x":234,"y":311,"w":134,"h":26},"dataType":"BATTERY"}]

/** The four cells inside the bottom pill, same shape as SLOTS. */
export const PILL_CELLS = [{"key":"temp","app":"WEATHER","dataType":"WEATHER_CURRENT","tap":{"x":12,"y":356,"w":92,"h":68,"src":"hit/92x68.png"},"value":{"x":12,"y":382,"w":92,"h":36,"size":28}},{"key":"kcal","app":"STATUS","dataType":"CAL","tap":{"x":104,"y":356,"w":92,"h":68,"src":"hit/92x68.png"},"value":{"x":104,"y":382,"w":92,"h":36,"size":28}},{"key":"stress","app":"PRESSURE","dataType":"STRESS","tap":{"x":196,"y":356,"w":92,"h":68,"src":"hit/92x68.png"},"value":{"x":196,"y":382,"w":92,"h":36,"size":28}},{"key":"pai","app":"PAI","dataType":"PAI_DAILY","tap":{"x":288,"y":356,"w":92,"h":68,"src":"hit/92x68.png"},"value":{"x":288,"y":382,"w":92,"h":36,"size":28}}]

export const METER_STEPS = 21

export const AOD = {
  x: 85,
  w: 220,
  timeY: 173,
  timeH: 46,
  timeSize: 34,
  dateY: 221,
  dateH: 22,
  dateSize: 17,
}
