/**
 * GENERATED by tools/build-assets.cjs — do not edit by hand.
 * Keeps the live widgets aligned with the baked-in background artwork.
 */

export const SCREEN = { w: 390, h: 450 }

export const COLOR = {
  bg: 0x000000,
  pink: 0xf24bcf,
  cyan: 0x0be0f2,
  white: 0xffffff,
  aodText: 0xc8c8d8,
}

export const IMAGE = {
  bg: 'bg.png',
  aod: 'aod.png',
  hourHighlight: (h) => 'hl/h' + (h < 10 ? '0' + h : h) + '.png',
  minuteHighlight: (m) => 'hl/m' + (m < 10 ? '0' + m : m) + '.png',
  meter: (name, step) => 'meter/' + name + '/' + (step < 10 ? '0' + step : step) + '.png',
  aodHourRing: 'hl/aod_h.png',
  aodMinuteRing: 'hl/aod_m.png',
}

export const TEMP_FONT = [
  'temp/0.png', 'temp/1.png', 'temp/2.png', 'temp/3.png', 'temp/4.png',
  'temp/5.png', 'temp/6.png', 'temp/7.png', 'temp/8.png', 'temp/9.png',
]
export const TEMP_DEGREE = 'temp/deg.png'
export const TEMP_NEGATIVE = 'temp/neg.png'
export const TEMP_INVALID = 'temp/dash.png'

/** Top-left corner of the 78x78 hour chip, per hour. */
export const HOUR_POS = [[213,2],[239,5],[263,15],[283,31],[299,52],[309,75],[312,101],[309,127],[299,151],[283,171],[263,187],[239,197],[213,200],[187,197],[164,187],[143,171],[127,151],[117,127],[114,101],[117,75],[127,51],[143,31],[163,15],[187,5]]
/** Top-left corner of the 60x60 minute chip, per minute. */
export const MINUTE_POS = [[222,76],[226,76],[229,77],[233,78],[236,79],[239,81],[242,82],[245,85],[247,87],[250,90],[251,93],[253,96],[254,99],[255,103],[256,106],[256,110],[256,114],[255,117],[254,121],[253,124],[251,127],[250,130],[247,133],[245,135],[242,138],[239,139],[236,141],[233,142],[229,143],[226,144],[222,144],[218,144],[215,143],[211,142],[208,141],[205,139],[202,138],[199,135],[197,133],[194,130],[193,127],[191,124],[190,121],[189,117],[188,114],[188,110],[188,106],[189,103],[190,99],[191,96],[193,93],[194,90],[197,87],[199,85],[202,82],[205,81],[208,79],[211,78],[215,77],[218,76]]
/** Same sprites, positioned around the centred AOD dial. */
export const AOD_HOUR_POS = [[156,21],[195,26],[231,41],[262,65],[286,96],[301,132],[306,171],[301,210],[286,246],[262,277],[231,301],[195,316],[156,321],[117,316],[81,301],[50,277],[26,246],[11,210],[6,171],[11,132],[26,96],[50,65],[81,41],[117,26]]
export const AOD_MINUTE_POS = [[165,98],[174,98],[182,100],[190,102],[198,105],[206,109],[213,114],[220,119],[226,125],[231,132],[236,139],[240,147],[243,155],[245,163],[247,171],[247,180],[247,189],[245,197],[243,205],[240,213],[236,221],[231,228],[226,235],[220,241],[213,246],[206,251],[198,255],[190,258],[182,260],[174,262],[165,262],[156,262],[148,260],[140,258],[132,255],[124,251],[117,246],[110,241],[104,235],[99,228],[94,221],[90,213],[87,205],[85,197],[83,189],[83,180],[83,171],[85,163],[87,155],[90,147],[94,139],[99,132],[104,125],[110,119],[117,114],[124,109],[132,105],[140,102],[148,100],[156,98]]

export const HL_HOUR_BOX = 78
export const HL_MIN_BOX = 60

/**
 * One entry per tile: the live value box, its optional trailing unit, the
 * heart-rate gauge or battery wave, the tap target, and the name of the system
 * app that a tap opens.
 */
export const SLOTS = [{"key":"hr","app":"HR","tap":{"src":"hit/100x78.png","x":12,"y":28,"w":100,"h":78},"value":{"x":21,"y":64,"w":48,"h":36,"size":28,"color":0xf24bcf},"unit":{"x":70,"y":76,"w":34,"h":24,"size":13,"color":0xffffff,"text":"BPM"},"meter":{"name":"hr","x":44,"y":39,"w":59,"h":14},"dataType":"HEART"},{"key":"distance","app":"STATUS","tap":{"src":"hit/100x78.png","x":12,"y":112,"w":100,"h":78},"value":{"x":21,"y":148,"w":56,"h":36,"size":28,"color":0xf24bcf},"unit":{"x":78,"y":160,"w":26,"h":24,"size":13,"color":0x7175ff,"text":"KM"},"meter":null,"dataType":"DISTANCE"},{"key":"steps","app":"STATUS","tap":{"src":"hit/100x78.png","x":12,"y":196,"w":100,"h":78},"value":{"x":21,"y":232,"w":82,"h":36,"size":28,"color":0xf24bcf},"unit":null,"meter":null,"dataType":"STEP"},{"key":"date","app":"CALENDAR","tap":{"src":"hit/100x68.png","x":12,"y":280,"w":100,"h":68},"value":{"x":21,"y":306,"w":82,"h":36,"size":24,"color":0xf24bcf},"unit":null,"meter":null,"dataType":null},{"key":"battery","app":"SETTING","tap":{"src":"hit/262x68.png","x":118,"y":280,"w":262,"h":68},"value":{"x":127,"y":306,"w":50,"h":36,"size":28,"color":0x0be0f2},"unit":null,"meter":{"name":"battery","x":180,"y":311,"w":191,"h":26},"dataType":"BATTERY"}]

/** The four cells inside the bottom pill, same shape as SLOTS. */
export const PILL_CELLS = [{"key":"temp","app":"WEATHER","dataType":"WEATHER_CURRENT","tap":{"x":12,"y":356,"w":92,"h":68,"src":"hit/92x68.png"},"value":{"x":12,"y":382,"w":92,"h":36,"size":28}},{"key":"kcal","app":"STATUS","dataType":"CAL","tap":{"x":104,"y":356,"w":92,"h":68,"src":"hit/92x68.png"},"value":{"x":104,"y":382,"w":92,"h":36,"size":28}},{"key":"stress","app":"PRESSURE","dataType":"STRESS","tap":{"x":196,"y":356,"w":92,"h":68,"src":"hit/92x68.png"},"value":{"x":196,"y":382,"w":92,"h":36,"size":28}},{"key":"pai","app":"PAI","dataType":"PAI_DAILY","tap":{"x":288,"y":356,"w":92,"h":68,"src":"hit/92x68.png"},"value":{"x":288,"y":382,"w":92,"h":36,"size":28}}]

export const METER_STEPS = 21

export const AOD = {
  x: 85,
  w: 220,
  timeY: 173,
  timeH: 46,
  timeSize: 34,
  dateY: 221,
  dateH: 22,
  dateSize: 17,
}
